version: '3'

networks:
  smartNotary-cc-net:
    external: true

services:
  goinitus:
    image: goledger/cc-webclient:latest
    container_name: goinitus
    ports:
      - "8080:80"
    networks:
      - smartNotary-cc-net
